In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
dataset = pd.read_csv('Import.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [20]:
print(x)

[['China' 95.0 40000000.0]
 ['Brazil' 92.0 36000000.0]
 ['Germany' 65.0 28000000.0]
 ['Brazil' 55.0 25000000.0]
 ['Germany' nan 32000000.0]
 ['Germany' 88.0 35000000.0]
 ['China' 73.0 29000000.0]
 ['China' 99.0 45000000.0]
 ['Brazil' 69.0 nan]]


In [21]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No']


In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [23]:
print(x)

[['China' 95.0 40000000.0]
 ['Brazil' 92.0 36000000.0]
 ['Germany' 65.0 28000000.0]
 ['Brazil' 55.0 25000000.0]
 ['Germany' 79.5 32000000.0]
 ['Germany' 88.0 35000000.0]
 ['China' 73.0 29000000.0]
 ['China' 99.0 45000000.0]
 ['Brazil' 69.0 33750000.0]]


In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[0.0 1.0 0.0 95.0 40000000.0]
 [1.0 0.0 0.0 92.0 36000000.0]
 [0.0 0.0 1.0 65.0 28000000.0]
 [1.0 0.0 0.0 55.0 25000000.0]
 [0.0 0.0 1.0 79.5 32000000.0]
 [0.0 0.0 1.0 88.0 35000000.0]
 [0.0 1.0 0.0 73.0 29000000.0]
 [0.0 1.0 0.0 99.0 45000000.0]
 [1.0 0.0 0.0 69.0 33750000.0]]


In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
print(y)

[1 1 0 0 1 0 0 1 0]


In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [30]:
print(x_train)

[[0.0 1.0 0.0 73.0 29000000.0]
 [0.0 1.0 0.0 99.0 45000000.0]
 [1.0 0.0 0.0 92.0 36000000.0]
 [0.0 1.0 0.0 95.0 40000000.0]
 [0.0 0.0 1.0 79.5 32000000.0]
 [1.0 0.0 0.0 55.0 25000000.0]
 [0.0 0.0 1.0 88.0 35000000.0]]


In [31]:
print(x_test)

[[1.0 0.0 0.0 69.0 33750000.0]
 [0.0 0.0 1.0 65.0 28000000.0]]


In [32]:
print(y_train)

[0 1 1 1 1 0 0]


In [33]:
print(y_test)

[0 0]


In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [36]:
print(x_train)

[[0.0 1.0 0.0 -0.7115950252820157 -0.8975602524508658]
 [0.0 1.0 0.0 1.1254304300559541 1.6800486776644397]
 [1.0 0.0 0.0 0.6308466536188084 0.23014365447458032]
 [0.0 1.0 0.0 0.8428111292347281 0.8745458870034067]
 [0.0 0.0 1.0 -0.2523386614475232 -0.41425857805424604]
 [1.0 0.0 0.0 -1.9833818789775333 -1.5419624849796922]
 [0.0 0.0 1.0 0.3482273527975823 0.06904309634237374]]


In [38]:
print(x_test)

[[1.0 0.0 0.0 -0.9942143261032418 -0.1323326013228845]
 [0.0 0.0 1.0 -1.276833626924468 -1.0586608105830724]]
